server:
  port: 80


#Eureka
eureka:
  client:
    #是否向eureka server 注册自己
    register-with-eureka: true
    #是否从EruekaServer 抓取已有的注册信息，如果是服务只有一个的话不存在，多个需要设置为true才能与ribbon进行负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

spring:
  application:
    name: consumer
