server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


spring:
  application:
    name: hystrix-consumer

#feign客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #建立连接所用的时间，适用于网络正常情况下，连东莞所连接的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectionTimeout: 5000

feign:
  hystrix:
    enabled: true