server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  #zk 配置
  cloud:
    zookeeper:
      connect-string: 192.168.31.81:2181

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.31.81:3306/cloud2020?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: Bin.ye.95@qq.com

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yb.entities