server:
  port: 9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: cloud-gateway-service

spring:
  application:
    name: cloud-gateway
    #配置网关
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由功能，利用微服务名称进行路由，不需要配置ip和端口
      routes:
        - id: payment_routh #路由的ID，没有固定的规则但要求唯一，建议配合服务名使用
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #上面开启从注册动态创建路由功能之后，配置的服务名
          predicates:
            - Path=/pay/payment/get/** #断言，路径相匹配的额进行路由
            #- After=2020-07-28T21:35:51.504+08:00[Asia/Shanghai] #时间之后生效
            #- Before=2020-07-28T21:35:51.504+08:00[Asia/Shanghai] #时间之前生效
            #- Between=2020-06-28T21:35:51.504+08:00[Asia/Shanghai],2020-07-28T21:35:51.504+08:00[Asia/Shanghai] #之间
            #- Cookie=username,yb #cookie 键值对  请求curl http://localhost:9527/pay/payment/get/1   --cookie "username=yb"
            #- Header=X-Request-Id, \d+  #请求头信息要有X-Request-Id 属性并且值为整数的正则表达式 curl http://localhost:9527/pay/payment/get/1   -H "X-Request-Id:123"
            #- Host= **.baidu.com   #请求的域名需要时**.baidu.com的
            #- Method=GET #请求方法
            #- Query=username, \d+ #要有参数是username并且值是整数的才能路由
          filters:
             - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加一对请求头，名为X-Request-Id，值为1024
        - id: payment_routh2 #路由的ID，没有固定的规则但要求唯一，建议配合服务名使用
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #上面开启从注册动态创建路由功能之后，配置的服务名
          predicates:
            - Path=/pay/test/lb/** #断言，路径相匹配的额进行路由