server:
  port: 8401

spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.81
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719 #默认端口8719 如果端口被占用，则依次+1直至找到没被占用的端口

management:
  endpoints:
    web:
      exposure:
        include: '*'
