server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #erueka 服务端实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false 表示自己是注册中心，职责是维护实例，不需要检索服务
    fetch-registry: false
    service-url:
        #设置与Eureka Server交互的地址
        defaultZone: http://eureka7002.com:7002/eureka/
  #关闭自我保护机制,确保间隔2秒清理一次不可用的服务
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000