server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.81
    #sentinel
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      #规则持久化到nacos配置
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.31.81 #nacos地址
            dataId: nacos-order-consumer #服务名称
            groupId: DEFAULT_GROUP #配置分组
            data_type: json
            rule_type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'